# promqtt Condfiguration

# Configuration related to the MQTT broker
mqtt:
  broker: mqtt
  port: 1883


# Configuration of the HTTP server
http:
  interface: 0.0.0.0
  port: 8086


# Available metrics
metrics:
  promqtt_pressure:
    type: gauge
    help: Air pressure in millibar
    timeout: 120
  promqtt_humidity:
    type: gauge
    help: Relative humidity in percent
    timeout: 120
  promqtt_temperature:
    type: gauge
    help: Temperature in degree celsius
    timeout: 120
  promqtt_rssi:
    type: gauge
    help: Relative wifi signal strength indicator
    timeout: 120
  promqtt_vcc:
    type: gauge
    help: Node supply voltage in volt
    timeout: 120
  promqtt_power:
    type: gauge
    help: Power state
    timeout: 120
  promqtt_battery:
    type: gauge
    help: Battery state in percent
    timeout: 120

    
types:
  aqara_node:
    promqtt_rssi:
      value: "{msg.data[linkquality]}"
      labels: { 'node': '{msg.topic_list[1]}', 'sensor': 'aqara' }
    promqtt_battery:
      value: "{msg.data[battery]}"
      labels: { 'node': '{msg.topic_list[1]}', 'sensor': 'aqara' }
    promqtt_vcc:
      measurement: "promqtt_vcc"
      value: "{msg.data[voltage]}"
      factor: 0.001
      offset: 0
      labels: { 'node': '{msg.topic_list[1]}', 'sensor': 'aqara' }

  # zigbee2mqtt/aqara_sens_1 {"temperature":25.99,"linkquality":86,
  # "humidity":45.86,"pressure":999,"battery":91,"voltage":2985}
  aqara_sensor:
    promqtt_temperature:
      value: "{msg.data[temperature]}"
      labels: { 'node': '{msg.topic_list[1]}', 'sensor': 'aqara' }

    promqtt_pressure:
      value: "{msg.data[pressure]}"
      labels: { 'node': '{msg.topic_list[1]}', 'sensor': 'aqara' }

    promqtt_humidity:
      value: "{msg.data[humidity]}"
      labels: { 'node': '{msg.topic_list[1]}', 'sensor': 'aqara' }


messages:
  
  - topics: ["re:zigbee2mqtt/aqara_(sw_01|sens_tph_01)"]
    parser: "json"
    types: ['aqara_node']
    
#  - topics: ["zigbee2mqtt/aqara_sens_tph_01"]
#    types: ['aqara_node', 'aqara_sensor']
#    parser: "json"
