name: Run quality assurance tasks

# We run on all branches and also for pull-requests
on:
  push: {}
  pull_request:
    branches:
      - master
      - develop

jobs:

  qa_checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the QA Docker image
      run: ./scripts/build_qa.sh

    - name: Run QA scripts
      run: ./scripts/qa.sh make qa
