name: Run quality assurance tasks

# We run on all branches and also for pull-requests
on:
  push: {}
  pull_request:
    branches:
      - master
      - develop

jobs:

  qa_checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker images
        run: docker build -t qa --file .devcontainer/Dockerfile .

      - name: Run tests
        run: docker run -v $PWD:/app -w /app qa bash -c "pipenv sync --dev; scripts/qa.sh"
